upstream market {
    server web:8000;
}

server {

    listen 80;

    location / {
        proxy_pass http://market;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;
    }

    location /static {
        autoindex on;
        alias /home/parisa/Desktop/market/market/static;
    }

}