# Generated by Django 5.1 on 2024-09-01 08:55

from django.db import migrations, models



class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('authorize', '0004_alter_user_country_code_alter_user_phone_number'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddConstraint(
                    model_name='user',
                    constraint=models.UniqueConstraint(
                        fields=('phone_number', 'country_code'),
                        name='Unique_Phone_Countrycode'),
                ),
            ],
            database_operations=[migrations.RunSQL(
                'ALTER TABLE "authorize_user" ADD CONSTRAINT  CONCURRENTLY'
                '"Unique_Phone_Countrycode" UNIQUE ("phone_number", '
                '"country_code")',
                reverse_sql='drop constraint Unique_Phone_Countrycode;'
            )],
        )
    ]
