# Generated by Django 5.1 on 2024-08-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorize', '0002_alter_user_country_code'),
    ]

    operations = [
    ]
